### ISSUE TITLE
ValueError: Values in `t_eval` are not within `t_span`.

### ISSUE THREAD

**Issue by raaperrotta** [ryansmcgee/seirsplus#11]
Floating point precision limitations can cause an error to be raised by the scipy solver when running a SEIRSModel. In the [models.py line 127](https://github.com/ryansmcgee/seirsplus/blob/f2b848465252f867d38684eab2674f2a854fd55a/seirsplus/models.py#L127), the end time is calculated as the current time plus the runtime. When the runtime is calculated as `runtime = self.tmax - self.t` (e.g. [models.py:line229](https://github.com/ryansmcgee/seirsplus/blob/f2b848465252f867d38684eab2674f2a854fd55a/seirsplus/models.py#L229)) this can result in the last value of `t_eval` being greater than `self.tmax` and therefore outside `t_span`. In other words, sometimes `self.t + (self.tmax - self.t) > self.tmax`.

I believe you could solve this by using `t_span` instead of `[self.t, self.tmax]` in [line 144](https://github.com/ryansmcgee/seirsplus/blob/f2b848465252f867d38684eab2674f2a854fd55a/seirsplus/models.py#L144).

**Comment by TripHumphrey** [comment]
I had the same issue and I just added 0.1 to the self.t+runtime value on line 130

**Comment by ryansmcgee** [comment]
Thank you both for raising this issue and possible fixes. I apologize for the long delay in pushing a fix. @raaperrotta's change is in effect for models.py and legacy_models.py as of v1.0.1.
