### ISSUE TITLE
typo in model eq.s with quarantine 

### ISSUE THREAD

**Issue by ggrrll** [ryansmcgee/seirsplus#16]
Hi,

- In 5th and 6th eq., the index of neigh. is wrong (`k`, instead of `j`)
- there should be also a `q` (missing) in the 2nd part of the 1st eq., right? (the part <img src="https://latex.codecogs.com/gif.latex?\sim(1-p)\beta_D" title="\sim(1-p)\beta_D" />)

![](https://github.com/ryansmcgee/seirsplus/blob/master/images/SEIRSnetworktesting_transitions.png)

Thanks for the package

**Comment by ryansmcgee** [comment]
Thank you for the notes. The previous model documentation is now completely replaced by the wiki (hopefully no new typos!)
