### ISSUE TITLE
copyright problem

### ISSUE THREAD

**Issue by sikuan** [ryansmcgee/seirsplus#22]
Hi,

I'm trying to packaging this into Debian as a Debian package, and now I'm writing the copyright information.

I found the copyright statement in LICENSE which seems missed ```year``` and ```fullname```.

https://github.com/ryansmcgee/seirsplus/blob/5c04080640a8a9716b19e8653d4e75523dd03074/LICENSE#L3

There supposes would be ```Copyright (c) 2020 Ryan Seamus McGee```.

Could you please let me know if this statement is correct or not and fix this?

Thank you~

**Comment by ryansmcgee** [comment]
Just fixed this, better late than never :)
