### ISSUE TITLE
'SymptomaticSEIRSNetworkModel' object has no attribute 'D_I_S'

### ISSUE THREAD

**Issue by billlyzhaoyh** [ryansmcgee/seirsplus#23]
When using NodeGroupData, these two lines in the SymptomaticSEIRSNetworkModel are standalone and self.D_I_S and Self.D_I_A don't seem to be defined anywhere else:

`self.nodeGroupData[groupName]['numD_I_S'][0]    = numpy.count_nonzero(self.nodeGroupData[groupName]['mask']*self.X==self.D_I_S)
                self.nodeGroupData[groupName]['numD_I_A'][0]    = numpy.count_nonzero(self.nodeGroupData[groupName]['mask']*self.X==self.D_I_A)`

**Comment by thefirebanks** [comment]
it appears as they should be `self.D_S` and `self.D_A` instead!

**Comment by ryansmcgee** [comment]
This class was de facto deprecated and is now no longer in the package.
