### ISSUE TITLE
Wiki typo about accessing sim results

### ISSUE THREAD

**Issue by mihaibanciu** [ryansmcgee/seirsplus#31]
There seems to be a typo below about accessing `Q_E` and `Q_I`. What is the proper way to access these -- is it something like `model.numQ_E` and `model.numQ_I`, respectively?

```
S = model.numS            # time series of S counts
E = model.numE            # time series of E counts
I = model.numI            # time series of I counts
R = model.numR            # time series of R counts
F = model.numF            # time series of F counts
Q_E = model.numE          # time series of Q_E counts
Q_I = model.numI          # time series of Q_I counts
```

**Comment by ryansmcgee** [comment]
Thanks for pointing this out. You are correct, it should be `model.numQ_E` and `model.numQ_I`. I also checked for typos in the same section on the other model class documentation pages and believe they're all correct now.

**Comment by mihaibanciu** [comment]
Also, the quarantine graph is defined as `G_Q` but referred to as `Q` in the examples (SEIRS dynamics on a network), if I'm not mistaken.
