### ISSUE TITLE
Update to text of Basic SEIRS Model Description

### ISSUE THREAD

**Issue by dennyglee** [ryansmcgee/seirsplus#32]
A quick suggestion to update the wiki text for [Basic SEIRS Model Description](https://github.com/ryansmcgee/seirsplus/wiki/SEIRS-Model-Description):

Below the SEIRS deterministic equations (under **Deterministic Mean-field Implementation**), suggest defining *F* and *N* , e.g.: `Note, F are the numbers of deceased individuals (fatalities) and N is the total number of individuals in the population.`

**Comment by ryansmcgee** [comment]
Updated, thank you for the suggestion!
