### ISSUE TITLE
Undefined name: 'self' in a non-method

### ISSUE THREAD

**Issue by cclauss** [ryansmcgee/seirsplus#5]
The current code has the potential to raise NameError at runtime.  This code was previously in a class method that defined `self` but when it was moved into a standalone function, the `self.` was not removed.

https://github.com/ryansmcgee/seirsplus/blob/master/seirsplus/models.py#L1194

$ `flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics`
```
./seirsplus/models.py:1194:49: F821 undefined name 'self'
        nodeDegrees = graph.sum(axis=0).reshape(self.numNodes,1)   # sums of adj matrix cols
                                                ^
```

**Comment by ryansmcgee** [comment]
Thanks for raising this issue!
The code has been change to:
``` python
# Get a list of the node degrees:
    if type(graph)==numpy.ndarray:
        nodeDegrees = graph.sum(axis=0).reshape((graph.shape[0],1))   # sums of adj matrix cols
```
